#!/bin/bash
echo -e "\x1b[32mClearing old programs...\x1b[0m"
./rmall
cp project.pros temp2

upload_file() {
    echo -e "\x1b[32mBuilding \x1b[1m$2\x1b[0m"
    echo "void autonomous() {$1();};" > src/mode.txt
    pros make || exit 1
    echo -e "\x1b[32mUploading \x1b[1m$2\x1b[0;32m to slot 1...\x1b[0m"
    cat project.pros | sed "s/\"project_name\": \"[^\"]*\"/\"project_name\": \"$3\"/" > temp
    mv temp project.pros
    sudo pros upload --slot $4
}
upload_file "auton_short" "Driver Left" "Left" 1
upload_file "auton_short_right" "Driver Right" "Right" 2
upload_file "auton_long" "Skills" "Skills" 3

mv temp2 project.pros
rm temp
